# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Electron Builder Action
      uses: samuelmeuli/action-electron-builder@v1.4.0
      with:
        # GitHub authentication token
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Whether the app should be released after a successful build
        release: false
        # Whether the action should execute the NPM build script before running `electron-builder`
        skip_build: true
